// ============================================================
// Animals — continents + their famous animals (the "Animals" island).
// ------------------------------------------------------------
// Each animal carries an English name, a Somali name (a sensible default the
// family can re-record / relabel), and a friendly emoji. The emoji is just the
// default picture — a real uploaded photo (Img slot 'animal-<id>') overrides
// it, so no copyrighted images are bundled.
//
// Somali names: real Somali where it's well-established; a clear Somali-spelled
// transliteration for animals Somali simply borrows. They're meant to be
// re-recorded by the family (Voiceover Studio → per animal).
//
// IDs carry a continent suffix (-af, -as, -eu, -na, -sa, -oc, -an) so every id
// is unique even when the same animal appears on more than one continent.
//
// A quiz session shuffles and serves up to 20 at a time, then reshuffles fresh
// ones on the next visit (see AppState.startContinent).
// ============================================================
import 'package:flutter/material.dart';

class Animal {
  final String id; // → Img slot 'animal-<id>' + VO ids 'animal-<id>-en/-so'
  final String en; // English name
  final String so; // Somali name (default; re-recordable)
  final String emoji; // friendly default picture
  const Animal(this.id, this.en, this.so, this.emoji);
}

class Continent {
  final String id;
  final String name;
  final String emoji; // a famous animal, shown on the map button
  final Color color; // map colour (mirrors the reference continents map)
  final List<Animal> pool;
  const Continent(this.id, this.name, this.emoji, this.color, this.pool);
}

Continent continentById(String id) => kContinents.firstWhere((c) => c.id == id);

const List<Continent> kContinents = [
  // =========================================================================
  Continent('africa', 'Africa', '🦁', Color(0xFFF2A03D), [
    Animal('lion-af', 'Lion', 'Libaax', '🦁'),
    Animal('leopard-af', 'Leopard', 'Shabeel', '🐆'),
    Animal('cheetah-af', 'Cheetah', 'Haramcad', '🐆'),
    Animal('elephant-af', 'Elephant', 'Maroodi', '🐘'),
    Animal('giraffe-af', 'Giraffe', 'Geri', '🦒'),
    Animal('zebra-af', 'Zebra', 'Dameer-dibadeed', '🦓'),
    Animal('rhino-af', 'Rhino', 'Wiyil', '🦏'),
    Animal('hippo-af', 'Hippo', 'Jeer', '🦛'),
    Animal('gorilla-af', 'Gorilla', 'Gorilla', '🦍'),
    Animal('chimp-af', 'Chimpanzee', 'Daanyeer-madow', '🐵'),
    Animal('baboon-af', 'Baboon', 'Daayeer', '🐒'),
    Animal('mandrill-af', 'Mandrill', 'Mandiril', '🐒'),
    Animal('lemur-af', 'Lemur', 'Leemuur', '🐒'),
    Animal('buffalo-af', 'Buffalo', 'Gisi', '🐃'),
    Animal('wildebeest-af', 'Wildebeest', 'Gnuu', '🐃'),
    Animal('gazelle-af', 'Gazelle', 'Cawl', '🦌'),
    Animal('impala-af', 'Impala', 'Impala', '🦌'),
    Animal('kudu-af', 'Kudu', 'Kuduu', '🦌'),
    Animal('oryx-af', 'Oryx', 'Biciid', '🦌'),
    Animal('springbok-af', 'Springbok', 'Springbog', '🦌'),
    Animal('antelope-af', 'Antelope', 'Deero', '🦌'),
    Animal('warthog-af', 'Warthog', 'Gadhqorre', '🐗'),
    Animal('hyena-af', 'Hyena', 'Waraabe', '🐺'),
    Animal('jackal-af', 'Jackal', 'Dacawo', '🦊'),
    Animal('wilddog-af', 'Wild Dog', 'Eey-duurjoog', '🐕'),
    Animal('caracal-af', 'Caracal', 'Karakaal', '🐈'),
    Animal('serval-af', 'Serval', 'Sarfaal', '🐈'),
    Animal('honeybadger-af', 'Honey Badger', 'Honey-badger', '🦡'),
    Animal('meerkat-af', 'Meerkat', 'Miirkaat', '🦫'),
    Animal('aardvark-af', 'Aardvark', 'Aardfaak', '🐽'),
    Animal('pangolin-af', 'Pangolin', 'Bangooliin', '🦔'),
    Animal('porcupine-af', 'Porcupine', 'Bortataw', '🦔'),
    Animal('hare-af', 'Hare', 'Bakayle', '🐰'),
    Animal('fruitbat-af', 'Fruit Bat', 'Fiidmeer', '🦇'),
    Animal('mongoose-af', 'Mongoose', 'Manguus', '🦫'),
    Animal('okapi-af', 'Okapi', 'Okaabi', '🦒'),
    Animal('camel-af', 'Camel', 'Geel', '🐪'),
    Animal('ostrich-af', 'Ostrich', 'Gorayo', '🐦'),
    Animal('flamingo-af', 'Flamingo', 'Flaamingo', '🦩'),
    Animal('vulture-af', 'Vulture', 'Gorgor', '🦅'),
    Animal('hornbill-af', 'Hornbill', 'Hornbil', '🐦'),
    Animal('grayparrot-af', 'Grey Parrot', 'Baqbaqaaq', '🦜'),
    Animal('guineafowl-af', 'Guineafowl', 'Diiqo', '🐓'),
    Animal('hoopoe-af', 'Hoopoe', 'Hud-hud', '🐦'),
    Animal('fisheagle-af', 'Fish Eagle', 'Gorgor-kalluun', '🦅'),
    Animal('kingfisher-af', 'Kingfisher', 'Dhuxulaqabe', '🐦'),
    Animal('crocodile-af', 'Crocodile', 'Yaxaas', '🐊'),
    Animal('python-af', 'Python', 'Mas-weyn', '🐍'),
    Animal('mamba-af', 'Black Mamba', 'Mas-madow', '🐍'),
    Animal('cobra-af', 'Cobra', 'Abeeso', '🐍'),
    Animal('chameleon-af', 'Chameleon', 'Qorrato', '🦎'),
    Animal('monitor-af', 'Monitor Lizard', 'Mulac-weyn', '🦎'),
    Animal('gecko-af', 'Gecko', 'Qorrato-yar', '🦎'),
    Animal('tortoise-af', 'Tortoise', 'Diin', '🐢'),
    Animal('dungbeetle-af', 'Dung Beetle', 'Duxulade', '🪲'),
    Animal('termite-af', 'Termite', 'Aboor', '🐜'),
    Animal('locust-af', 'Locust', 'Ayax', '🦗'),
    Animal('scorpion-af', 'Scorpion', 'Hangarallo', '🦂'),
    Animal('butterfly-af', 'Butterfly', 'Balanbaalis', '🦋'),
    Animal('honeybee-af', 'Honeybee', 'Shinni', '🐝'),
    Animal('mosquito-af', 'Mosquito', 'Kaneeco', '🦟'),
    Animal('penguin-af', 'African Penguin', 'Pingwiin', '🐧'),
    Animal('greatwhite-af', 'Great White Shark', 'Libaax-badeed', '🦈'),
    Animal('dolphin-af', 'Dolphin', 'Dolfin', '🐬'),
    Animal('whale-af', 'Whale', 'Nibiri', '🐳'),
    Animal('seaturtle-af', 'Sea Turtle', 'Diin-badeed', '🐢'),
    Animal('seal-af', 'Cape Fur Seal', 'Nibiri-yar', '🦭'),
    Animal('crab-af', 'Crab', 'Carsaanyo', '🦀'),
    Animal('catfish-af', 'Catfish', 'Kalluun', '🐟'),
    Animal('tilapia-af', 'Tilapia', 'Tilaabiya', '🐟'),
  ]),
  // =========================================================================
  Continent('asia', 'Asia', '🐼', Color(0xFFB9A6E0), [
    Animal('panda-as', 'Giant Panda', 'Panda', '🐼'),
    Animal('redpanda-as', 'Red Panda', 'Panda-cas', '🦝'),
    Animal('tiger-as', 'Tiger', 'Tiigar', '🐯'),
    Animal('snowleopard-as', 'Snow Leopard', 'Shabeel-baraf', '🐆'),
    Animal('leopard-as', 'Leopard', 'Shabeel', '🐆'),
    Animal('cloudedleopard-as', 'Clouded Leopard', 'Shabeel-daruur', '🐆'),
    Animal('asiaticlion-as', 'Asiatic Lion', 'Libaax', '🦁'),
    Animal('elephant-as', 'Asian Elephant', 'Maroodi', '🐘'),
    Animal('rhino-as', 'Indian Rhino', 'Wiyil', '🦏'),
    Animal('waterbuffalo-as', 'Water Buffalo', 'Gisi', '🐃'),
    Animal('yak-as', 'Yak', 'Yaak', '🐂'),
    Animal('gaur-as', 'Gaur', 'Gawr', '🐃'),
    Animal('bactrian-as', 'Bactrian Camel', 'Geel', '🐫'),
    Animal('slothbear-as', 'Sloth Bear', 'Orso', '🐻'),
    Animal('sunbear-as', 'Sun Bear', 'Orso-yar', '🐻'),
    Animal('blackbear-as', 'Asian Black Bear', 'Orso-madow', '🐻'),
    Animal('orangutan-as', 'Orangutan', 'Daanyeer-cas', '🦧'),
    Animal('gibbon-as', 'Gibbon', 'Gibon', '🐒'),
    Animal('macaque-as', 'Macaque', 'Makaak', '🐒'),
    Animal('langur-as', 'Langur', 'Languur', '🐒'),
    Animal('proboscis-as', 'Proboscis Monkey', 'Daanyeer-san', '🐒'),
    Animal('deer-as', 'Deer', 'Deero', '🦌'),
    Animal('sambar-as', 'Sambar Deer', 'Deero-weyn', '🦌'),
    Animal('muskdeer-as', 'Musk Deer', 'Deero-uunsi', '🦌'),
    Animal('markhor-as', 'Markhor', 'Markor', '🐐'),
    Animal('ibex-as', 'Ibex', 'Riyo-dibadeed', '🐐'),
    Animal('takin-as', 'Takin', 'Taakin', '🐂'),
    Animal('pangolin-as', 'Pangolin', 'Bangooliin', '🦔'),
    Animal('civet-as', 'Civet', 'Siibad', '🦡'),
    Animal('dhole-as', 'Dhole', 'Eey-duureed', '🐕'),
    Animal('wildass-as', 'Wild Ass', 'Dameer-dibadeed', '🐎'),
    Animal('flyingsquirrel-as', 'Flying Squirrel', 'Dabagaalle-duula', '🐿️'),
    Animal('slowloris-as', 'Slow Loris', 'Looris', '🐒'),
    Animal('tarsier-as', 'Tarsier', 'Taarsiye', '🐒'),
    Animal('komodo-as', 'Komodo Dragon', 'Komodo', '🦎'),
    Animal('gharial-as', 'Gharial', 'Yaxaas-san', '🐊'),
    Animal('muggercroc-as', 'Mugger Crocodile', 'Yaxaas', '🐊'),
    Animal('kingcobra-as', 'King Cobra', 'Abeeso-boqor', '🐍'),
    Animal('indianpython-as', 'Indian Python', 'Mas-weyn', '🐍'),
    Animal('viper-as', 'Viper', 'Jararab', '🐍'),
    Animal('monitor-as', 'Monitor Lizard', 'Mulac-weyn', '🦎'),
    Animal('peacock-as', 'Peacock', 'Daawus', '🦚'),
    Animal('hornbill-as', 'Hornbill', 'Hornbil', '🐦'),
    Animal('myna-as', 'Myna', 'Mayna', '🐦'),
    Animal('kingfisher-as', 'Kingfisher', 'Dhuxulaqabe', '🐦'),
    Animal('crane-as', 'Crane', 'Karaan', '🕊️'),
    Animal('pheasant-as', 'Pheasant', 'Fiisan', '🐓'),
    Animal('junglefowl-as', 'Junglefowl', 'Diiqo-duur', '🐓'),
    Animal('vulture-as', 'Vulture', 'Gorgor', '🦅'),
    Animal('eagle-as', 'Eagle', 'Gorgor', '🦅'),
    Animal('owl-as', 'Owl', 'Guumeys', '🦉'),
    Animal('parakeet-as', 'Parakeet', 'Baqbaqaaq', '🦜'),
    Animal('butterfly-as', 'Butterfly', 'Balanbaalis', '🦋'),
    Animal('silkworm-as', 'Silkworm', 'Dirira', '🐛'),
    Animal('honeybee-as', 'Honeybee', 'Shinni', '🐝'),
    Animal('scorpion-as', 'Scorpion', 'Hangarallo', '🦂'),
    Animal('tarantula-as', 'Tarantula', 'Caaro-weyn', '🕷️'),
    Animal('whaleshark-as', 'Whale Shark', 'Libaax-badeed', '🦈'),
    Animal('dugong-as', 'Dugong', 'Loh-badeed', '🦭'),
    Animal('riverdolphin-as', 'River Dolphin', 'Dolfin-webi', '🐬'),
    Animal('seaturtle-as', 'Sea Turtle', 'Diin-badeed', '🐢'),
    Animal('clownfish-as', 'Clownfish', 'Kalluun-midabley', '🐠'),
    Animal('pufferfish-as', 'Pufferfish', 'Kalluun-buufis', '🐡'),
    Animal('crab-as', 'Crab', 'Carsaanyo', '🦀'),
    Animal('prawn-as', 'Prawn', 'Camuun', '🦐'),
    Animal('squid-as', 'Squid', 'Sicid', '🦑'),
    Animal('octopus-as', 'Octopus', 'Faro-badeed', '🐙'),
    Animal('jellyfish-as', 'Jellyfish', 'Yuuy-badeed', '🪼'),
  ]),
  // =========================================================================
  Continent('europe', 'Europe', '🦊', Color(0xFFC8A98C), [
    Animal('fox-eu', 'Red Fox', 'Dawaco', '🦊'),
    Animal('wolf-eu', 'Grey Wolf', 'Yey', '🐺'),
    Animal('bear-eu', 'Brown Bear', 'Orso', '🐻'),
    Animal('lynx-eu', 'Lynx', 'Liinks', '🐈'),
    Animal('wildcat-eu', 'Wildcat', 'Bisad-duureed', '🐈'),
    Animal('reddeer-eu', 'Red Deer', 'Deero-cas', '🦌'),
    Animal('roedeer-eu', 'Roe Deer', 'Deero', '🦌'),
    Animal('fallowdeer-eu', 'Fallow Deer', 'Deero-bar', '🦌'),
    Animal('reindeer-eu', 'Reindeer', 'Deero-baraf', '🦌'),
    Animal('moose-eu', 'Elk', 'Muus', '🫎'),
    Animal('bison-eu', 'European Bison', 'Gisi-weyn', '🦬'),
    Animal('chamois-eu', 'Chamois', 'Shamwaa', '🐐'),
    Animal('ibex-eu', 'Ibex', 'Riyo-buureed', '🐐'),
    Animal('mouflon-eu', 'Mouflon', 'Wan-duureed', '🐏'),
    Animal('boar-eu', 'Wild Boar', 'Doofaar', '🐗'),
    Animal('badger-eu', 'Badger', 'Bajar', '🦡'),
    Animal('otter-eu', 'Otter', 'Dige', '🦦'),
    Animal('beaver-eu', 'Beaver', 'Biifar', '🦫'),
    Animal('hedgehog-eu', 'Hedgehog', 'Cawsharaar', '🦔'),
    Animal('squirrel-eu', 'Red Squirrel', 'Dabagaalle', '🐿️'),
    Animal('hare-eu', 'Hare', 'Bakayle', '🐰'),
    Animal('rabbit-eu', 'Rabbit', 'Bakayle-guri', '🐰'),
    Animal('dormouse-eu', 'Dormouse', 'Jiir-hurda', '🐭'),
    Animal('stoat-eu', 'Stoat', 'Istoot', '🦦'),
    Animal('weasel-eu', 'Weasel', 'Wiisal', '🦦'),
    Animal('pinemarten-eu', 'Pine Marten', 'Maartin', '🦦'),
    Animal('hamster-eu', 'Hamster', 'Haamstar', '🐹'),
    Animal('bat-eu', 'Bat', 'Fiidmeer', '🦇'),
    Animal('horse-eu', 'Horse', 'Faras', '🐎'),
    Animal('donkey-eu', 'Donkey', 'Dameer', '🐴'),
    Animal('goat-eu', 'Goat', 'Ri', '🐐'),
    Animal('sheep-eu', 'Sheep', 'Wan', '🐑'),
    Animal('owl-eu', 'Owl', 'Guumeys', '🦉'),
    Animal('goldeneagle-eu', 'Golden Eagle', 'Gorgor-dahabi', '🦅'),
    Animal('falcon-eu', 'Falcon', 'Shimbir-ugaadhsi', '🦅'),
    Animal('robin-eu', 'Robin', 'Robin', '🐦'),
    Animal('sparrow-eu', 'Sparrow', 'Shimbir-yar', '🐦'),
    Animal('swallow-eu', 'Swallow', 'Dabbaaldeg', '🐦'),
    Animal('blackbird-eu', 'Blackbird', 'Shimbir-madow', '🐦‍⬛'),
    Animal('magpie-eu', 'Magpie', 'Magbay', '🐦'),
    Animal('raven-eu', 'Raven', 'Tuke', '🐦‍⬛'),
    Animal('stork-eu', 'Stork', 'Babahaad', '🐦'),
    Animal('swan-eu', 'Swan', 'Berde', '🦢'),
    Animal('duck-eu', 'Mallard Duck', 'Boorad', '🦆'),
    Animal('goose-eu', 'Goose', 'Wadbahar', '🪿'),
    Animal('woodpecker-eu', 'Woodpecker', 'Geed-tume', '🐦'),
    Animal('puffin-eu', 'Puffin', 'Bafin', '🐧'),
    Animal('viper-eu', 'Adder', 'Jararab', '🐍'),
    Animal('grasssnake-eu', 'Grass Snake', 'Mas-doog', '🐍'),
    Animal('lizard-eu', 'Lizard', 'Qorrato', '🦎'),
    Animal('frog-eu', 'Frog', 'Rah', '🐸'),
    Animal('toad-eu', 'Toad', 'Rah-dhul', '🐸'),
    Animal('salamander-eu', 'Salamander', 'Salamandar', '🦎'),
    Animal('honeybee-eu', 'Honeybee', 'Shinni', '🐝'),
    Animal('butterfly-eu', 'Butterfly', 'Balanbaalis', '🦋'),
    Animal('ladybird-eu', 'Ladybird', 'Caayimad', '🐞'),
    Animal('ant-eu', 'Ant', 'Qudhaanjo', '🐜'),
    Animal('snail-eu', 'Snail', 'Snayl', '🐌'),
  ]),
  // =========================================================================
  Continent('north_america', 'North America', '🦅', Color(0xFFE36A6A), [
    Animal('baldeagle-na', 'Bald Eagle', 'Gorgor-madax-cad', '🦅'),
    Animal('grizzly-na', 'Grizzly Bear', 'Orso-weyn', '🐻'),
    Animal('blackbear-na', 'Black Bear', 'Orso-madow', '🐻'),
    Animal('polarbear-na', 'Polar Bear', 'Orso-baraf', '🐻‍❄️'),
    Animal('bison-na', 'American Bison', 'Gisi-weyn', '🦬'),
    Animal('wolf-na', 'Grey Wolf', 'Yey', '🐺'),
    Animal('coyote-na', 'Coyote', 'Kooyoot', '🐺'),
    Animal('redfox-na', 'Red Fox', 'Dawaco', '🦊'),
    Animal('arcticfox-na', 'Arctic Fox', 'Dawaco-baraf', '🦊'),
    Animal('cougar-na', 'Cougar', 'Shabeel-buureed', '🐆'),
    Animal('bobcat-na', 'Bobcat', 'Bobkat', '🐈'),
    Animal('lynx-na', 'Lynx', 'Liinks', '🐈'),
    Animal('moose-na', 'Moose', 'Muus', '🫎'),
    Animal('elk-na', 'Elk', 'Deero-weyn', '🦌'),
    Animal('whitetail-na', 'White-tailed Deer', 'Deero', '🦌'),
    Animal('caribou-na', 'Caribou', 'Deero-baraf', '🦌'),
    Animal('pronghorn-na', 'Pronghorn', 'Cawl-mareykan', '🦌'),
    Animal('bighorn-na', 'Bighorn Sheep', 'Wan-gees-weyn', '🐏'),
    Animal('mountaingoat-na', 'Mountain Goat', 'Ri-buureed', '🐐'),
    Animal('muskox-na', 'Musk Ox', 'Dibi-uunsi', '🐂'),
    Animal('beaver-na', 'Beaver', 'Biifar', '🦫'),
    Animal('raccoon-na', 'Raccoon', 'Rakuun', '🦝'),
    Animal('opossum-na', 'Opossum', 'Obosum', '🐀'),
    Animal('skunk-na', 'Skunk', 'Sukunk', '🦨'),
    Animal('porcupine-na', 'Porcupine', 'Bortataw', '🦔'),
    Animal('groundhog-na', 'Groundhog', 'Jiir-dhul', '🐹'),
    Animal('prairiedog-na', 'Prairie Dog', 'Jiir-bannaan', '🐿️'),
    Animal('chipmunk-na', 'Chipmunk', 'Jibmunk', '🐿️'),
    Animal('squirrel-na', 'Squirrel', 'Dabagaalle', '🐿️'),
    Animal('jackrabbit-na', 'Jackrabbit', 'Bakayle-weyn', '🐰'),
    Animal('cottontail-na', 'Cottontail', 'Bakayle', '🐰'),
    Animal('armadillo-na', 'Armadillo', 'Armadilo', '🦔'),
    Animal('manatee-na', 'Manatee', 'Saca-badeed', '🦭'),
    Animal('seaotter-na', 'Sea Otter', 'Dige-badeed', '🦦'),
    Animal('harborseal-na', 'Seal', 'Nibiri-yar', '🦭'),
    Animal('walrus-na', 'Walrus', 'Walras', '🦭'),
    Animal('alligator-na', 'Alligator', 'Yaxaas', '🐊'),
    Animal('rattlesnake-na', 'Rattlesnake', 'Mas-shanqar', '🐍'),
    Animal('gartersnake-na', 'Garter Snake', 'Mas-yar', '🐍'),
    Animal('gilamonster-na', 'Gila Monster', 'Mulac-sun', '🦎'),
    Animal('iguana-na', 'Iguana', 'Iguana', '🦎'),
    Animal('snappingturtle-na', 'Snapping Turtle', 'Diin-qaniinyo', '🐢'),
    Animal('bullfrog-na', 'Bullfrog', 'Rah-weyn', '🐸'),
    Animal('turkey-na', 'Wild Turkey', 'Turki', '🦃'),
    Animal('horneddowl-na', 'Great Horned Owl', 'Guumeys-gees', '🦉'),
    Animal('hawk-na', 'Red-tailed Hawk', 'Haad', '🦅'),
    Animal('condor-na', 'Condor', 'Gorgor-weyn', '🦅'),
    Animal('bluejay-na', 'Blue Jay', 'Shimbir-buluug', '🐦'),
    Animal('cardinal-na', 'Cardinal', 'Shimbir-cas', '🐦'),
    Animal('hummingbird-na', 'Hummingbird', 'Shimbir-guuto', '🐦'),
    Animal('roadrunner-na', 'Roadrunner', 'Shimbir-orod', '🐦'),
    Animal('pelican-na', 'Pelican', 'Baalaq', '🐦'),
    Animal('canadagoose-na', 'Canada Goose', 'Wadbahar', '🪿'),
    Animal('loon-na', 'Loon', 'Luun', '🦆'),
    Animal('monarch-na', 'Monarch Butterfly', 'Balanbaalis-boqor', '🦋'),
    Animal('firefly-na', 'Firefly', 'Dab-shidaale', '🐛'),
    Animal('humpback-na', 'Humpback Whale', 'Nibiri', '🐳'),
    Animal('orca-na', 'Orca', 'Orka', '🐋'),
    Animal('dolphin-na', 'Dolphin', 'Dolfin', '🐬'),
    Animal('salmon-na', 'Salmon', 'Saalmon', '🐟'),
  ]),
  // =========================================================================
  Continent('south_america', 'South America', '🦥', Color(0xFF8FBBE8), [
    Animal('jaguar-sa', 'Jaguar', 'Jaaguar', '🐆'),
    Animal('puma-sa', 'Puma', 'Buuma', '🐆'),
    Animal('ocelot-sa', 'Ocelot', 'Oselot', '🐈'),
    Animal('sloth-sa', 'Sloth', 'Sloodh', '🦥'),
    Animal('anteater-sa', 'Giant Anteater', 'Cun-qudhaanjo', '🦡'),
    Animal('armadillo-sa', 'Armadillo', 'Armadilo', '🦔'),
    Animal('llama-sa', 'Llama', 'Lama', '🦙'),
    Animal('alpaca-sa', 'Alpaca', 'Albaaka', '🦙'),
    Animal('vicuna-sa', 'Vicuña', 'Fikuunya', '🦙'),
    Animal('guanaco-sa', 'Guanaco', 'Gwanako', '🦙'),
    Animal('capybara-sa', 'Capybara', 'Kabibaara', '🦫'),
    Animal('tapir-sa', 'Tapir', 'Taabir', '🐗'),
    Animal('giantotter-sa', 'Giant Otter', 'Dige-weyn', '🦦'),
    Animal('coati-sa', 'Coati', 'Kowaati', '🦝'),
    Animal('kinkajou-sa', 'Kinkajou', 'Kinkaju', '🦝'),
    Animal('marmoset-sa', 'Marmoset', 'Maarmoset', '🐒'),
    Animal('capuchin-sa', 'Capuchin Monkey', 'Daanyeer-kabuushin', '🐒'),
    Animal('howler-sa', 'Howler Monkey', 'Daanyeer-qaylo', '🐒'),
    Animal('spidermonkey-sa', 'Spider Monkey', 'Daanyeer-caaro', '🐒'),
    Animal('squirrelmonkey-sa', 'Squirrel Monkey', 'Daanyeer-yar', '🐒'),
    Animal('tamarin-sa', 'Tamarin', 'Taamarin', '🐒'),
    Animal('manedwolf-sa', 'Maned Wolf', 'Yey-cas', '🐺'),
    Animal('peccary-sa', 'Peccary', 'Doofaar-yar', '🐗'),
    Animal('agouti-sa', 'Agouti', 'Aguti', '🦫'),
    Animal('chinchilla-sa', 'Chinchilla', 'Jinjiila', '🐭'),
    Animal('andeanbear-sa', 'Spectacled Bear', 'Orso-okoyaal', '🐻'),
    Animal('toucan-sa', 'Toucan', 'Tuukaan', '🦜'),
    Animal('macaw-sa', 'Scarlet Macaw', 'Baqbaqaaq-cas', '🦜'),
    Animal('parrot-sa', 'Parrot', 'Baqbaqaaq', '🦜'),
    Animal('hummingbird-sa', 'Hummingbird', 'Shimbir-guuto', '🐦'),
    Animal('condor-sa', 'Andean Condor', 'Gorgor-weyn', '🦅'),
    Animal('harpyeagle-sa', 'Harpy Eagle', 'Gorgor-haarbi', '🦅'),
    Animal('rhea-sa', 'Rhea', 'Riya', '🐦'),
    Animal('ibis-sa', 'Ibis', 'Aybis', '🐦'),
    Animal('flamingo-sa', 'Flamingo', 'Flaamingo', '🦩'),
    Animal('anaconda-sa', 'Anaconda', 'Mas-weyn', '🐍'),
    Animal('boa-sa', 'Boa Constrictor', 'Boow', '🐍'),
    Animal('caiman-sa', 'Caiman', 'Yaxaas', '🐊'),
    Animal('poisonfrog-sa', 'Poison Dart Frog', 'Rah-sun', '🐸'),
    Animal('iguana-sa', 'Iguana', 'Iguana', '🦎'),
    Animal('rivetturtle-sa', 'River Turtle', 'Diin-webi', '🐢'),
    Animal('piranha-sa', 'Piranha', 'Biraanya', '🐟'),
    Animal('electriceel-sa', 'Electric Eel', 'Kalluun-koronto', '🐟'),
    Animal('arapaima-sa', 'Arapaima', 'Arabaayma', '🐟'),
    Animal('riverdolphin-sa', 'Amazon River Dolphin', 'Dolfin-webi', '🐬'),
    Animal('manatee-sa', 'Manatee', 'Saca-badeed', '🦭'),
    Animal('morpho-sa', 'Blue Morpho', 'Balanbaalis-buluug', '🦋'),
    Animal('leafcutter-sa', 'Leafcutter Ant', 'Qudhaanjo', '🐜'),
    Animal('tarantula-sa', 'Tarantula', 'Caaro-weyn', '🕷️'),
  ]),
  // =========================================================================
  Continent('oceania', 'Oceania', '🦘', Color(0xFF8FD49A), [
    Animal('kangaroo-oc', 'Kangaroo', 'Kangaruu', '🦘'),
    Animal('wallaby-oc', 'Wallaby', 'Walaabi', '🦘'),
    Animal('koala-oc', 'Koala', 'Koowala', '🐨'),
    Animal('wombat-oc', 'Wombat', 'Wombat', '🦡'),
    Animal('platypus-oc', 'Platypus', 'Bilaatibas', '🦫'),
    Animal('echidna-oc', 'Echidna', 'Ekidna', '🦔'),
    Animal('tasdevil-oc', 'Tasmanian Devil', 'Shaydaan-tasmaani', '🦡'),
    Animal('dingo-oc', 'Dingo', 'Dingo', '🐕'),
    Animal('quokka-oc', 'Quokka', 'Kowka', '🐹'),
    Animal('sugarglider-oc', 'Sugar Glider', 'Duule-macaan', '🐿️'),
    Animal('possum-oc', 'Possum', 'Bosum', '🐀'),
    Animal('bandicoot-oc', 'Bandicoot', 'Bandikuut', '🐀'),
    Animal('cassowary-oc', 'Cassowary', 'Kasaweri', '🐦'),
    Animal('emu-oc', 'Emu', 'Iimuu', '🐦'),
    Animal('kookaburra-oc', 'Kookaburra', 'Kukabura', '🐦'),
    Animal('cockatoo-oc', 'Cockatoo', 'Kokatuu', '🦜'),
    Animal('galah-oc', 'Galah', 'Gaalah', '🦜'),
    Animal('budgerigar-oc', 'Budgerigar', 'Bajariigar', '🦜'),
    Animal('lorikeet-oc', 'Lorikeet', 'Loorikiit', '🦜'),
    Animal('kiwi-oc', 'Kiwi', 'Kiiwi', '🐦'),
    Animal('kea-oc', 'Kea', 'Kee', '🦜'),
    Animal('lyrebird-oc', 'Lyrebird', 'Shimbir-laybar', '🐦'),
    Animal('blackswan-oc', 'Black Swan', 'Berde-madow', '🦢'),
    Animal('fairypenguin-oc', 'Little Penguin', 'Pingwiin-yar', '🐧'),
    Animal('saltiecroc-oc', 'Saltwater Crocodile', 'Yaxaas-badeed', '🐊'),
    Animal('freshiecroc-oc', 'Freshwater Crocodile', 'Yaxaas', '🐊'),
    Animal('frilledlizard-oc', 'Frilled Lizard', 'Mulac-gaaban', '🦎'),
    Animal('bluetongue-oc', 'Blue-tongued Skink', 'Mulac-carrab-buluug', '🦎'),
    Animal('thornydevil-oc', 'Thorny Devil', 'Mulac-qodxan', '🦎'),
    Animal('goanna-oc', 'Goanna', 'Gwaana', '🦎'),
    Animal('carpetpython-oc', 'Carpet Python', 'Mas-weyn', '🐍'),
    Animal('taipan-oc', 'Taipan', 'Taaybaan', '🐍'),
    Animal('treefrog-oc', 'Green Tree Frog', 'Rah-cagaar', '🐸'),
    Animal('greatwhite-oc', 'Great White Shark', 'Libaax-badeed', '🦈'),
    Animal('reefshark-oc', 'Reef Shark', 'Libaax-badeed-yar', '🦈'),
    Animal('mantaray-oc', 'Manta Ray', 'Manta', '🐟'),
    Animal('clownfish-oc', 'Clownfish', 'Kalluun-midabley', '🐠'),
    Animal('dugong-oc', 'Dugong', 'Lohbadeed', '🦭'),
    Animal('seaturtle-oc', 'Sea Turtle', 'Diin-badeed', '🐢'),
    Animal('dolphin-oc', 'Dolphin', 'Dolfin', '🐬'),
    Animal('humpback-oc', 'Humpback Whale', 'Nibiri', '🐳'),
    Animal('jellyfish-oc', 'Jellyfish', 'Yuuy-badeed', '🪼'),
    Animal('octopus-oc', 'Octopus', 'Faro-badeed', '🐙'),
    Animal('seahorse-oc', 'Seahorse', 'Faras-badeed', '🐠'),
    Animal('stingray-oc', 'Stingray', 'Kalluun-fud', '🐟'),
    Animal('starfish-oc', 'Starfish', 'Xiddig-badeed', '⭐'),
  ]),
  // =========================================================================
  Continent('antarctica', 'Antarctica', '🐧', Color(0xFFAFC4CC), [
    Animal('emperor-an', 'Emperor Penguin', 'Pingwiin-boqor', '🐧'),
    Animal('adelie-an', 'Adélie Penguin', 'Pingwiin-adeeli', '🐧'),
    Animal('gentoo-an', 'Gentoo Penguin', 'Pingwiin-gentoo', '🐧'),
    Animal('chinstrap-an', 'Chinstrap Penguin', 'Pingwiin-garbo', '🐧'),
    Animal('king-an', 'King Penguin', 'Pingwiin-boqornimo', '🐧'),
    Animal('weddell-an', 'Weddell Seal', 'Nibiri-yar', '🦭'),
    Animal('leopardseal-an', 'Leopard Seal', 'Nibiri-shabeel', '🦭'),
    Animal('crabeater-an', 'Crabeater Seal', 'Nibiri-carsaanyo', '🦭'),
    Animal('elephantseal-an', 'Elephant Seal', 'Nibiri-weyn', '🦭'),
    Animal('furseal-an', 'Fur Seal', 'Nibiri-dhogor', '🦭'),
    Animal('orca-an', 'Orca', 'Orka', '🐋'),
    Animal('bluewhale-an', 'Blue Whale', 'Nibiri-buluug', '🐳'),
    Animal('humpback-an', 'Humpback Whale', 'Nibiri', '🐳'),
    Animal('minke-an', 'Minke Whale', 'Nibiri-yar', '🐳'),
    Animal('krill-an', 'Krill', 'Kuril', '🦐'),
    Animal('icefish-an', 'Icefish', 'Kalluun-baraf', '🐟'),
    Animal('squid-an', 'Squid', 'Sicid', '🦑'),
    Animal('albatross-an', 'Albatross', 'Albatros', '🐦'),
    Animal('petrel-an', 'Snow Petrel', 'Shimbir-baraf', '🐦'),
    Animal('skua-an', 'Skua', 'Sakuwa', '🐦'),
  ]),
];
